.PHONY: lint test install-tools

lint:
	go fmt ./...
	golint ./...
	go vet ./...
	errcheck ./...
	gocyclo -over 10 .

test:
	go test -v -tags integration ./...

install-tools:
	go install github.com/matryer/moq
